before_install: gem install bundler --pre
before_script:
  - "bundle exec rake test_app"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - kennyadsl@gmail.com
branches:
  only:
    - 3-0-stable
rvm:
  - 2.1
